version: '3.8'

services:
  backend:
    image: ${DOCKER_HUB_USERNAME}/topfoodnow-backend:latest
    build: ./back-end
    container_name: topfoodnow_backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://topfoodnow-db.czm2ykk8gv7r.ap-southeast-2.rds.amazonaws.com:3306/mydb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Taipei&useSSL=false
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcs-key.json
      - REDIS_HOST=redis
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=Aa123456
      - APP_BASE_URL=http://54.253.115.242:4000/
    depends_on:
      - redis
    networks:
      - topfoodnow_network

  frontend:
    image: ${DOCKER_HUB_USERNAME}/topfoodnow-frontend:latest
    build: ./front-end
    container_name: topfoodnow_frontend
    restart: always
    ports:
      - "4000:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - backend
    networks:
      - topfoodnow_network

  redis:
    image: redis:alpine
    container_name: topfoodnow_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - topfoodnow_network

networks:
  topfoodnow_network:
    driver: bridge

volumes:
  redis_data: