name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Build with Maven
        run: mvn -f ./back-end/pom.xml clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create GCS Key File
        run: echo "${{ secrets.GCS_KEY_JSON }}" > back-end/src/main/resources/gcs-key.json

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./back-end
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/topfoodnow-backend:latest

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./front-end
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/topfoodnow-frontend:latest
          build-args: |
            VITE_API_BASE_URL=${{ secrets.APP_BACK_END_URL }}

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TOPFOODNOW_EC2_HOST }}
          username: ${{ secrets.TOPFOODNOW_EC2_USERNAME }}
          key: ${{ secrets.TOPFOODNOW_EC2_KEY }}
          script: |
            # 1. Navigate to the project directory
            cd /home/azureuser/TopFoodNow

            # 2. Pull the latest code from your GitHub repository
            # This command requires your VM to be configured with SSH keys to access the repo
            git pull

            # 3. Stop and remove old containers and images
            sudo docker compose down --rmi all

            # 4. Rebuild and restart the services
            # The --build flag will now work because the files are present
            sudo docker compose up -d --build
